<div class="clearfix">
<?= ($this->user_id) ? '<a class="button" href="/account">My Account</a>' : '<a class="button" href="/login">Login</a>' ?>
</div>
<?php 
	foreach($this->projects as $project) {
		echo '<div class="project clearfix">';
		echo '<p><strong>Title:</strong> ' . $project['title'] . '</p>';
		echo '<p><strong>URL:</strong> ' . $project['url'] . '</p>';
		echo '<p><strong>Date Completed:</strong> ' . $project['date_completed'] . '</p>';
		echo '<p><strong>Specs:</strong> ' . $project['specs'] . '</p>';
		echo '<p><strong>Approach:</strong> ' . $project['approach'] . '</p>';
		echo '<a class="button" href="/index/project/id/' . $project['id'] . '">View Project</a>';
		echo '</div>';	
	}
?>