<p>This is the Public view <?= ($this->user_id) ? '<a href="/account">My Account</a>' : '<a href="/login">Login</a>' ?></p> 
<?php 
	foreach($this->projects as $project) {
		echo '<div class="project">';
		echo '<p>Title: ' . $project['title'] . '</p>';
		echo '<p>URL: ' . $project['url'] . '</p>';
		echo '<p>Date Completed: ' . $project['date_completed'] . '</p>';
		echo '<p>Specs: ' . $project['specs'] . '</p>';
		echo '<p>Approach: ' . $project['approach'] . '</p>';
		echo '<a href="/index/project/id/' . $project['id'] . '">View Project</a>';
		echo '</div>';	
	}
?>