<h1>You added: <?= $this->project_title ?></h1>
<p><?= $this->project_title ?></p>
<p><?= $this->url ?></p>
<p><?= $this->author_first ?></p>
<p><?= $this->author_last ?></p>
<p><?= $this->class_name ?></p>
<p><?= $this->complete_date ?></p>

<p><?= $this->photoshop ?></p>
<p><?= $this->illustrator ?></p>
<p><?= $this->flash ?></p>
<p><?= $this->flex ?></p>
<p><?= $this->air ?></p>

<p><?= $this->html ?></p>
<p><?= $this->css ?></p>
<p><?= $this->javascript ?></p>
<p><?= $this->jquery ?></p>
<p><?= $this->php ?></p>

<p><?= $this->ror ?></p>
<p><?= $this->as2 ?></p>
<p><?= $this->as3 ?></p>
<p><?= $this->sql ?></p>
<p><?= $this->assign ?></p>
<p><?= $this->project ?></p>
