<form action="/image/addimage/id/<?= $this->project_id ?>" method="post" name="userGeneralSubmit" id="userGeneralSubmit" class="userGeneralSubmit">
    <fieldset>
        <legend>Thumbnail Images:</legend>
        
        <label>Thumbnail #1 (262px by 295px)</label>
        <input type="hidden" name="MAX_FILE_SIZE" value="400" />
        <input type="file" name="thumbnailOne" class="thumbnailOne" id="thumbnailOne" />
        
        <label>Thumbnail #2 (300px by 118px)</label>
        <input type="hidden" name="MAX_FILE_SIZE" value="400" />
        <input type="file" name="thumbnailTwo" class="thumbnailTwo" id="thumbnailTwo" />
    </fieldset>
    
    
    <fieldset>
        <legend>Fullscreen Images: (1280px by 800px)</legend>
        
        <label>FullScreen #1</label>
        <input type="hidden" name="MAX_FILE_SIZE" value="400" />
        <input type="file" name="thumbnailOne" class="thumbnailOne" id="thumbnailOne" />
        
        <label>FullScreen #2</label>
        <input type="hidden" name="MAX_FILE_SIZE" value="400" />
        <input type="file" name="thumbnailTwo" class="thumbnailTwo" id="thumbnailTwo" />
    </fieldset>

    <input type="submit" name="submitImageForm" value="submit" id="submitImageForm" class="submitImageForm" />
</form>

