<!--

-->

<h1>Add A Project</h1>
<a href="/account">Cancel</a>
<form action="/project/create" method="post" name="userGeneralSubmit" id="userGeneralSubmit" class="userGeneralSubmit">
        <fieldset>
            <legend>Project details:</legend>
            <label>Project Title</label>
            <input type="text" name="projectTitle" id="projectTitle" class="projectTitle" />
            
            <label>Project URL</label>
            <input type="text" name="projectUrl" id="projectUrl" class="projectUrl" />
        </fieldset>
        
        <fieldset>
            <legend>Project Authors:</legend>
            <label>First Name</label>
            <input type="text" name="authorFirstName" id="authorFirstName" class="authorFirstName" />
            <label>Last Name</label>
            <input type="text" name="authorLastName" id="authorLastName" class="authorLastName" />
        </fieldset>
        
        <fieldset>
            <legend>Class / Time:</legend>
            <label>Class</label>
            <input type="text" name="class" id="class" class="class" />
            
            <label>Date Completed</label>
            <input type="text" name="dateComplete" id="dateComplete" class="dateComplete" />
            
        </fieldset>
        
        
        <fieldset>
        
            <legend>Tools used:</legend>
            
                  
            <input type="checkbox" name="photoshop" id="photoshop" class="check" value="photoshop" />
            <label>Photoshop</label>
            
            
            <input type="checkbox" name="illustrator" id="illustrator" class="check" value="illustrator" />
            <label>Illustrator</label>
            
            
            <input type="checkbox" name="flash" id="flash" class="check" value="flash" />
            <label>Flash</label>
            
            
            <input type="checkbox" name="flex" id="flex" class="check" value="flex" />
            <label>Flex</label>
            
            
            <input type="checkbox" name="air" id="air" class="check" value="air" />
            <label>Air</label>
       </fieldset>

       <fieldset>

               <legend>Languages:</legend>
       
               <input type="checkbox" name="html" id="html" class="check" value="html" />
            <label>HTML</label>      
            
            <input type="checkbox" name="css" id="css" class="check" value="css" /> 
            <label>CSS</label>
           
            <input type="checkbox" name="javascript" id="javascript" class="check" value="javascript" />
            <label>Javascript</label>
            
            <input type="checkbox" name="jquery" id="jquery" class="check" value="jquery" />
            <label>jQuery</label><br />
            
            <input type="checkbox" name="php" id="php" class="check" value="php" />
            <label>PHP</label>
            
            <input type="checkbox" name="ror" id="ror" class="check" value="ror" />
            <label>ROR</label>
            
            <input type="checkbox" name="as2" id="as2" class="check" value="as2"/>
            <label>Actionscript 2.0</label><br />
            
            <input type="checkbox" name="as3" id="as3" class="check"  value="as3"/>
            <label>Actionscript 3.0</label>
            
            <input type="checkbox" name="sql" id="sql" class="check" value="sql" />
            <label>mySQL</label>
            
       </fieldset>
   
       <fieldset>
        <label>Assignment Specifications:</label>
           <textarea name="assigmentSpecs" id="assigmentSpecs" wrap="hard"></textarea>

        
        <label>Project Approach:</label>
        <textarea name="projectApproach" id="projectApproach" wrap="hard"></textarea>
        
        <input type="submit" name="submitGeneralForm" value="submit" id="submitGeneralForm" class="submitGeneralForm" />
   
     </fieldset>
</form>
