<form action="/account/create" method="post">
	<fieldset>
		<legend>Create an account</legend>
			<label for="first_name">First Name</label>
			<input type="text" name="first_name" id="first_name" />
			<label for="last_name">Last Name</label>
			<input type="text" name="last_name" id="last_name" />
			<label for="email">Email</label>
			<input type="text" name="email" id="email" />
			<label for="password">Password</label>
			<input type="text" name="password" id="password" />
			<label for="confirm_password">Confirm Password</label>
			<input type="text" name="confirm_password" id="confirm_password" />
			<label for="security_question">Security Question</label>
			<input type="text" name="security_question" id="security_question" />
			<label for="security_answer">Security Answer</label>
			<input type="text" name="security_answer" id="security_answer" />
			<button type="submit">Submit</button>
	</fieldset>
</form>
<a class="button" href="/index">Cancel</a>
