<p>A Project</p>
<a href="/account">Cancel</a>
<h1>Edit "<?= $this->project['title'] ?>"</h1>
<div class="project_images">
<?php
	foreach($this->project['images'] as $image) {
		echo "<img src=\"/uploads/{$image['file_name']}\" />";
	}
?>
</div>
<a href="/account/addimages/id/<?= $this->project['id'] ?>">Edit Images</a>
<form action="/project/update/id/<?= $this->project['id'] ?>" method="post" name="userGeneralSubmit" id="userGeneralSubmit" class="userGeneralSubmit">
        <fieldset>
            <legend>Project details:</legend>
            <label>Project Title</label>
            <input type="text" name="projectTitle" id="projectTitle" class="projectTitle" value="<?= $this->project['title'] ?>"/>
            
            <label>Project URL</label>
            <input type="text" name="projectUrl" id="projectUrl" class="projectUrl"  value="<?= $this->project['url'] ?>"/>
        </fieldset>
        
        <fieldset>
            <legend>Project Authors:</legend>
            <label>First Name</label>
            <input type="text" name="authorFirstName" id="authorFirstName" class="authorFirstName"  value="<?= $this->project['author']['first_name'] ?>"/>
            <label>Last Name</label>
            <input type="text" name="authorLastName" id="authorLastName" class="authorLastName" value="<?= $this->project['author']['last_name'] ?>"/>
        </fieldset>
        
        <fieldset>
            <legend>Class / Time:</legend>
            <label>Class</label>
            <input type="text" name="class" id="class" class="class" value="<?= $this->project['class'] ?>"/>
            
            <label>Date Completed</label>
            <input type="text" name="dateComplete" id="dateComplete" class="dateComplete" value="<?= $this->project['date_completed'] ?>"/>
            
        </fieldset>
     
		<fieldset>
        
            <legend>Tools used:</legend>
            
                  
            <input type="checkbox" name="photoshop" id="photoshop" class="check" value="photoshop" <?= (isset($this->project['tools']['photoshop'])) ? 'checked = checked' : ''?>/>
            <label>Photoshop</label>
            
            
            <input type="checkbox" name="illustrator" id="illustrator" class="check" value="illustrator" <?= (isset($this->project['tools']['illustrator'])) ? 'checked = checked' : ''?> />
            <label>Illustrator</label>
            
            
            <input type="checkbox" name="flash" id="flash" class="check" value="flash" <?= (isset($this->project['tools']['flash'])) ? 'checked = checked' : ''?> />
            <label>Flash</label>
            
            
            <input type="checkbox" name="flex" id="flex" class="check" value="flex" <?= (isset($this->project['tools']['flex'])) ? 'checked = checked' : ''?> />
            <label>Flex</label>
            
            
            <input type="checkbox" name="air" id="air" class="check" value="air" <?= (isset($this->project['tools']['air'])) ? 'checked = checked' : ''?> />
            <label>Air</label>
       </fieldset>

       <fieldset>

            <legend>Languages:</legend>
       
            <input type="checkbox" name="html" id="html" class="check" value="html" <?= (isset($this->project['language']['html'])) ? 'checked = checked' : ''?>/>
            <label>HTML</label>      
            
            <input type="checkbox" name="css" id="css" class="check" value="css" <?= (isset($this->project['language']['css'])) ? 'checked = checked' : ''?>/> 
            <label>CSS</label>
           
            <input type="checkbox" name="javascript" id="javascript" class="check" value="javascript" <?= (isset($this->project['language']['javascript'])) ? 'checked = checked' : ''?>/>
            <label>Javascript</label>
            
            <input type="checkbox" name="jquery" id="jquery" class="check" value="jquery" <?= (isset($this->project['language']['jquery'])) ? 'checked = checked' : ''?>/>
            <label>jQuery</label><br />
            
            <input type="checkbox" name="php" id="php" class="check" value="php" <?= (isset($this->project['language']['php'])) ? 'checked = checked' : ''?>/>
            <label>PHP</label>
            
            <input type="checkbox" name="ror" id="ror" class="check" value="ror" <?= (isset($this->project['language']['ror'])) ? 'checked = checked' : ''?>/>
            <label>ROR</label>
            
            <input type="checkbox" name="as2" id="as2" class="check" value="as2"<?= (isset($this->project['language']['as2'])) ? 'checked = checked' : ''?>/>
            <label>Actionscript 2.0</label><br />
            
            <input type="checkbox" name="as3" id="as3" class="check"  value="as3" <?= (isset($this->project['language']['as3'])) ? 'checked = checked' : ''?>/>
            <label>Actionscript 3.0</label>
            
            <input type="checkbox" name="sql" id="sql" class="check" value="sql" <?= (isset($this->project['language']['sqsl'])) ? 'checked = checked' : ''?>/>
            <label>mySQL</label>
            
       </fieldset>
   
       <fieldset>
        <label>Assignment Specifications:</label>
           <textarea name="assigmentSpecs" id="assigmentSpecs" wrap="hard"><?= $this->project['specs'] ?></textarea>

        
        <label>Project Approach:</label>
        <textarea name="projectApproach" id="projectApproach" wrap="hard"><?= $this->project['approach'] ?></textarea>
        
        <input type="submit" name="submitGeneralForm" value="update" id="submitGeneralForm" class="submitGeneralForm" />
   
     </fieldset>
</form>
