<form method="post" name="userGeneralSubmit" id="userGeneralSubmit" class="userGeneralSubmit">
        <fieldset>
            <legend>Admin Login</legend>
            
            <label>Username</label>
            <input type="text" name="adminUser" id="adminUser" class="adminUser" />
            
            <label>Password</label>
            <input type="text" name="adminPassword" id="adminPassword" class="adminPassword" />
            
            <input type="submit" name="loginAdmin" value="login" id="loginAdmin" class="loginAdmin" />
           
        </fieldset>
</form>