<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" />
	<title>Application</title>
	
	<link type="text/css" href="/css/master.css" rel="stylesheet" />
	<link type="text/css" href="/css/general.css" rel="stylesheet" />
</head>

<body>
	<div id="container" class="clearfix">
	<h1 id="logo"><img src="/images/logo.png" /></h1>
		<?= $this->layout()->content ?>
	</div>
</body>
</html>